spring.application.name=FundDataMnager


spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/fund_manager?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.hikari.max-lifetime=60000
